### PR TITLE
Add more fields

### PR DESCRIPTION
**Pull request by in-session**
company, position, xing and linkedin

### CODE REVIEW

**Comment by cdaecke** [comment]
Thanks for contributing!
Do you mind, changing the field "companie" to company? Afterwards I would merge your changes.

**Comment by in-session** [comment]
Hi ok i changed the fields companie into company and also the itemprob of the postion and Company inside the Show.html

**Comment by cdaecke** [comment]
Thanks a lot!

**Comment by in-session** [comment]
Sorry two points are wrong, now it works.

**Pull request merged**
